codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 0%
        base: auto
        informational: false
    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "**/tests.rs"
  - "src/main.rs"