name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install GTK dependencies
      run: |
        sudo apt-get update
        # Add the Ubuntu 22.04 repository that contains GTK4
        sudo add-apt-repository -y ppa:ubuntu-desktop/ppa
        sudo apt-get update
        # Install GTK3, GTK4, and other required dependencies
        sudo apt-get install -y libgtk-3-dev libgtk-4-dev libglib2.0-dev libgraphene-1.0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
